### ISSUE TITLE
Cant find dial code?

### ISSUE THREAD

**Issue by kjbaker-uk** [rakeshkr114/DummyPhone#1]
Hello, I am having a look at this project as I also wanted to make an app that launches when a number has been dialed. I can't see where you have put that code that launches it?

if(getIntent().getData()!=null)

Where is this defined?

**Comment by rakeshkr114** [comment]
Hi, You need to add tag "intent-filter" in your [activity_main.xml](https://github.com/rakeshkr114/DummyPhone/blob/master/app/src/main/res/layout/activity_main.xml) for intent.action.DIAL.
And then you can use it in any application for dial intent. Ref: [ImplicitIntents](https://github.com/rakeshkr114/AndroidStudioProjects/blob/master/ImplicitIntents/app/src/main/java/com/example/m1039158/implicitintents/MainActivity.java).

**Comment by kjbaker-uk** [comment]
Hi, Thank you for your reply. I'm sorry I do not understand. Do you have a completed example? I am trying to launch my app when I dial a number on the phone.

Kind Regards
